-- Type for attendance_status
CREATE TYPE attendance_status_type AS ENUM (
    'INCOMPLETE',
    'PRESENT',
    'ABSENT'
);

-- Create attendance table
CREATE TABLE attendance (
    id UUID PRIMARY KEY,                        -- generated by Spring Boot

    employee_ref_id UUID NOT NULL,              -- FK to employees.id
    attendance_date DATE NOT NULL,              -- one record per employee per day

    check_in_time TIMESTAMP NOT NULL,            -- daily check-in time
    check_out_time TIMESTAMP,                    -- daily check-out time (nullable)

    working_minutes INTEGER,                    -- total working time in minutes
    attendance_status attendance_status_type NOT NULL,

    created_by VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(50),
    updated_at TIMESTAMP,

    CONSTRAINT uq_employee_attendance_day
        UNIQUE (employee_ref_id, attendance_date),

    CONSTRAINT fk_attendance_employee
        FOREIGN KEY (employee_ref_id)
        REFERENCES employees(id)
);

--add default generate id for test data
ALTER TABLE attendance
ALTER COLUMN id SET DEFAULT gen_random_uuid();

-- Index for date-based queries (reports, filters)
CREATE INDEX idx_attendance_date
    ON attendance(attendance_date);

-- Composite index for employee + date queries
CREATE INDEX idx_attendance_employee_date
    ON attendance(employee_ref_id, attendance_date);
