-- Drop tables only in dev
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS departments;

-- Create departments table
CREATE TABLE departments (
    id UUID PRIMARY KEY,                       -- generated by Spring Boot
    department_id VARCHAR(10) UNIQUE NOT NULL, -- public/external ID
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_by VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(50),
    updated_at TIMESTAMP
);

-- Create employees table
CREATE TABLE employees (
    id UUID PRIMARY KEY,                        -- generated by Spring Boot
    employee_id VARCHAR(10) UNIQUE,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone_number VARCHAR(20) NOT NULL UNIQUE,
    job_title VARCHAR(50) NOT NULL,
    employment_status VARCHAR(20) NOT NULL,
    department_ref_id UUID NOT NULL,
    manager_id VARCHAR(10),
    created_by VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(50),
    updated_at TIMESTAMP,
    CONSTRAINT fk_department
        FOREIGN KEY (department_ref_id)
        REFERENCES departments(id)
);
